### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by Prof-Seifert** [Nervengift/kvvliveapi#18]
KVV changed stations on 12.12.2021.
The API call results in no data.

**Comment by MrJFry** [comment]
@Prof-Seifert 
They just changed their STOPIDs.
You can find your new STOPID here: 
[https://live.kvv.de/webapp/stops/all?key=377d840e54b59adbe53608ba1aad70e8] 
Just replace the STOPID in the API with the new one, and it should work again.

**Comment by Prof-Seifert** [comment]
@Nervengift @MrJFry 
We use the API https://live.kvv.de/webapp/ further on, again since Dec. 21, 21 - the repsonses are OK.
