### ISSUE TITLE
INFRA-632 Trams don't work reliably

### ISSUE THREAD

**Issue by balohmatevz** [Nervengift/kvvliveapi#7]
The tram system failed today on several services. Initially I observed 404: Missing resource errors on some services, this lasted for about an hour. Afterwards service was partially restored, but round trip ping-pong times were much longer than expected (upwards of 20 minutes longer than usual). This caused numerous connections to timeout and clients to drop. 

Unfortunately I don't know exactly how to reproduce this issue, but hope this is sufficient information to help you fix the problem. While I like the provided services, I would prefer if you test the trams more internally before releasing them to production. Thanks.

**Comment by Nervengift** [comment]
I do not host the API. These are only API bindings and documentation.

These errors you see are a problem of our local public transport companie's servers (and yes, they are quite unrealiable sometimes) and I can't do anything about it.

You may want to check the EFA ("elektronische Fahrplanauskunft") which offers data for Karlsruhe, too, iirc.
